package flc.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a single group exercise lesson at the Furzefield Leisure Centre.
 * A lesson has a maximum capacity of 4 members.
 */
public class Lesson {
    

    public static final int MAX_CAPACITY = 4;

    private final String lessonId;
    private final ExerciseType exerciseType;
    private final Day day;
    private final TimeSlot timeSlot;
    private final int weekNumber;
    private final List<Member> enrolledMembers;
    private final List<Review> reviews;

    public Lesson(String lessonId, ExerciseType exerciseType, Day day, TimeSlot timeSlot, int weekNumber) {
        this.lessonId = lessonId;
        this.exerciseType = exerciseType;
        this.day = day;
        this.timeSlot = timeSlot;
        this.weekNumber = weekNumber;
        this.enrolledMembers = new ArrayList<>();
        this.reviews = new ArrayList<>();
    }

    public String getLessonId() {
        return lessonId;
    }

    public ExerciseType getExerciseType() {
        return exerciseType;
    }

    public Day getDay() {
        return day;
    }

    public TimeSlot getTimeSlot() {
        return timeSlot;
    }

    public int getWeekNumber() {
        return weekNumber;
    }

    public double getPrice() {
        return exerciseType.getPrice();
    }

    public int getEnrolledCount() {
        return enrolledMembers.size();
    }

    public List<Member> getEnrolledMembers() {
        return new ArrayList<>(enrolledMembers);
    }

    public boolean hasSpace() {
        return enrolledMembers.size() < MAX_CAPACITY;
    }

    public boolean isEnrolled(Member member) {
        return enrolledMembers.contains(member);
    }

    public boolean addMember(Member member) {
        if (!hasSpace() || enrolledMembers.contains(member)) {
            return false;
        }
        enrolledMembers.add(member);
        return true;
    }

    public boolean removeMember(Member member) {
        return enrolledMembers.remove(member);
    }

    public List<Review> getReviews() {
        return new ArrayList<>(reviews);
    }

    public void addReview(Review review) {
        reviews.add(review);
    }

    /**
     * Calculates the average rating from all reviews for this lesson.
     * Returns 0.0 if no reviews exist.
     */
    public double getAverageRating() {
        if (reviews.isEmpty()) {
            return 0.0;
        }
        int sum = 0;
        for (Review r : reviews) {
            sum += r.getRating();
        }
        return (double) sum / reviews.size();
    }

    /**
     * Calculates the total income generated by this lesson.
     */
    public double getTotalIncome() {
        return enrolledMembers.size() * exerciseType.getPrice();
    }

    @Override
    public String toString() {
        return String.format("Week%d | %s | %s | %s | £%.2f | %d/%d enrolled",
                weekNumber, day, timeSlot.getDisplayName(),
                exerciseType, getPrice(), getEnrolledCount(), MAX_CAPACITY);
    }
}
